parameters:
    security.user_checker.class: Kspu\LdapBundle\Security\UserChecker

fr3d_ldap:
    service:
        ldap_manager:  kspu.ldap.ldap_manager
    driver:
        host: ldap.kspu.ru
    user:
        baseDn: dc=kspu,dc=ru
        attributes:
            - { ldap_attr: uid,  user_method: setUsername }
            - { ldap_attr: cn,  user_method: setFio }

security:
    firewalls:
        dev: #dirty
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            pattern:    ^/app/
            anonymous: true
            switch_user: true
            fr3d_ldap: ~
            form_login:
                login_path: /app/login/
                check_path: /app/login/check
                require_previous_session: false
                always_use_default_target_path: false
                default_target_path: /app/
                csrf_provider: form.csrf_provider
            logout:
                path:   /app/logout/
                target: /