services:
    kspu.ldap.listener.ldap:
        class: Kspu\LdapBundle\Mappings\Ldap\LdapListener
        arguments:
            - @service_container
        calls:
            - [setAnnotationReader, [@annotation_reader]]
        tags:
            - {name: doctrine.event_subscriber, connection: default}
    kspu.ldap.validator.ldap_exists:
        class: Kspu\LdapBundle\Validator\LdapExistsValidator
        arguments:
            - @fr3d_ldap.ldap_manager
        tags:
            - { name: validator.constraint_validator, alias: kspu.ldap.validator.ldap_exists}
    kspu.ldap.ldap_manager:
        class: Kspu\LdapBundle\Ldap\LdapManager
        arguments:
            - @fr3d_ldap.ldap_driver
            - @fr3d_ldap.user_manager
            - %fr3d_ldap.ldap_manager.parameters%
    kspu.ldap.user_listener:
        class: Kspu\LDAP\Entity\UserListener
        arguments: [ @kspu_ldap.user_store ]
        tags:
            - { name: kernel.event_subscriber }
